### ISSUE TITLE
html file in subfolder fails to resolve node_modules correctly

### ISSUE THREAD

**Issue by spidgorny** [letorbi/tarp.require#16]
URL: http://localhost:8080/test/mongo.html
Script:
```
const require = Tarp.require;
require('mongorito');
```
Error: require.js:111 GET http://localhost:8080/test/node_modules/mongorito.js 404 (Not Found)
Notice that the real ```node_modules``` folder is one level above the ```test``` folder and not inside it.
How to fix that?

**Comment by letorbi** [comment]
Hej spidgorny,

thanks for reporting. I've pushed a fix into the *tarp* branch, that makes the `node_modules` path configurable. [The paths section in the updated readme](https://github.com/letorbi/tarp.require/blob/tarp/README.md#change-the-node_modules-path-globally) tells you how.

Please note that the fix in not part of the *master* branch, yet. I didn't merged it, because I'm still not 100% sure about the way to apply config-option to Tarp.require. Would be grat if you could test my fix and give some feedback.

Bye,
Torben

**Comment by letorbi** [comment]
Fixed bz 5ab9a600d01cbe05ffc44bd050d5e368a6c1aedf
