### ISSUE TITLE
Warning about Synchronous XMLHttpRequest in Firefox

### ISSUE THREAD

**Issue by unquietwiki** [letorbi/tarp.require#17]
https://xhr.spec.whatwg.org/#the-open()-method

However you're implementing this, is apparently in danger of being dropped in future browsers.

**Comment by letorbi** [comment]
Hi Michael,

I'm aware of the depreciation problem, that's why I've added the asynchronous loading feature to Tarp.require. As long as you load the main module(s) of your website with `Tarp.require('mymainmodule', true);`, all submodules will be loaded asynchronously. More details can be found in the ["Synchronous and asynchronous loading" section of the readme file](https://github.com/letorbi/tarp.require#synchronous-and-asynchronous-loading).

The synchronous load is more like a fallback for cases where asynchrionous loading cannot be applied. You're right it's obsolte, but since a lot of website still require it, it is quite unlikely that it is dropped.

Regards,
Torben

**Comment by letorbi** [comment]
I've added a hint about the importance of aynchronous loading to the readme.

**Comment by unquietwiki** [comment]
@letorbi Thanks!
