### ISSUE TITLE
"SCRIPT1086: Module import or export statement unexpected here     require.min.js (2,170)"

### ISSUE THREAD

**Issue by DragonOsman** [letorbi/tarp.require#18]
The title shows my current error in the console for an app I'm trying to build.

My HTML is as it is in this Gist, except I have my actual Key in the file on disc: https://gist.github.com/DragonOsman/506bd2bae1dfe4c03a4bbe2a6d830324

And my main script file is called scripts.js, which is as it is here: https://gist.github.com/DragonOsman/c6e8fb15343544e662f474c5a526d1c2

The file `country-currency-map.js` is a Node module.  Please help me fix this issue.

Edit: I also have an error saying:
```
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - http://localhost:8080/node_modules/node_modules/country-currency-map/country-currency-map.js

 SCRIPT5022: http://localhost:8080/node_modules/node_modules/country-currency-map/country-currency-map.js 404
```

I have the correct path mentioned in the call to `require` in my script file.  And the script file itself that I'm using as my main script is a client-side script.

**Comment by letorbi** [comment]
Hej Osman,

thanks for reporting - I'll will investigate the issue ASAP.

Just to be sure: You are using the [country-currency-map package from NPM](https://www.npmjs.com/package/country-currency-map), right? And can you tell me in what browser the issue occurred?

Bye
Torben

**Comment by DragonOsman** [comment]
The browser is MS Edge.  And it's a package that's in NPM, but I got it from the Payscale GitHub.

**Comment by DragonOsman** [comment]
By the way, one problem is that the path mentioned in the error message isn't where I'm placing the `node_modules` folder.

**Comment by letorbi** [comment]
> By the way, one problem is that the path mentioned in the error message isn't where I'm placing the node_modules folder.

Yeah, I've got that and will check it as well. Actually I'm quite packed with work now, so don't expect a solution before the weekend. Sorry about that :/

**Comment by DragonOsman** [comment]
It's okay, I'll wait.

**Comment by letorbi** [comment]
Hej Osman,

I finally had some time to check your code. It turned out that you had two errors in the first version of your code:

1. There is no need to load the script via `<script src="resources/scripts.js" type="text/javascript"></script>`, since your script will be loaded via `<script>Tarp.require("./resources/scripts.js", true);</script>`.

2. If you laod a global module there is no need to add `node_modules/...` to the module path. So lines like `require('node_modules/country-currency-map/country-currency-map.js')` have to changed to `require('country-currency-map/country-currency-map.js')`

The second version of you code doesn't seem to use Tarp.require at all. At least I didn't find any references to it in the code. Instead you seem to use *node_modules/es6-shim/es6-shim.js* to handle to module loading...
