### ISSUE TITLE
Function in main module is not begin recognized in index.html

### ISSUE THREAD

**Issue by geoffreyvd** [letorbi/tarp.require#20]
So I have an on-click button on index.html, which refers to a function in the main.js module, which can't be seen.

**Comment by letorbi** [comment]
Yeah, that is wanted behaviour since all modules run in their own scope. So a function that is "global" within a module is not part of the real global scope.

There is an easy way is to add variables and function from a module to the global scope. Just write `window.myFunction = function() {...}` instead of `function myFunction() {...}`. A HTML-statement like `<button onclick="myFunction();">` should work then.

Adding properties to the window-object with statements like `window.foo = "bar"` is the same as writing `var foo = "bar"` in the global scope (when you are not in a function or module), so the solution I'm suggesting is no hack or anything.

**Comment by letorbi** [comment]
An alternative approach would be to access the button from within the module. You just have to be sure, that the DOM-tree has been loaded, yet.

To use `myFunction()` as a click-handler for a button with the ID `MyButton`, you could add the following lines at the end for you module:

```
window.addEventListener("load", function() {
  document.getElementById("MyButton").addEventListener("click", myFunction);
});
```

IMHO this is a cleaner solution since it doesn't pullute the global scope.

**Comment by geoffreyvd** [comment]
@letorbi Hi thank you for your response, that indeed makes sense, nice one! 
Maybe add this to documentation?

**Comment by letorbi** [comment]
Hi @geoffreyvd, great that I could help you :) I will add a note about exporting to the global scope to the docs soon.

PS: I made some updates to my code example above to make sure that the DOM-elements are linked to the module-functions even if the module-code is executed after the page has been loaded.
