### ISSUE TITLE
Does not work on local files

### ISSUE THREAD

**Issue by jeberger** [letorbi/tarp.require#25]
`require` does not work if the scrips are loaded locally (ie. if loaded from a `file:///whatever.html` page). This appears to be due to the fact that local files don't specify a mime type and that `XMLHttpRequest` then assumes that the files are XML and attempts to parse them as such.

Adding `request.overrideMimeType('text/javascript');` just before `request.open("GET", href, asyn);` appears to fix the problem.

**Comment by letorbi** [comment]
Actually I never planned to make Tarp.require compatible with local files, because of two reasons: 1st most browser don't allow to get local files via `XMLHttpRequest` by default and 2nd Tarp.require relies partly on the server to resolve module IDs (see "HTTP redirects").

Therefore I don't think that support for local files will land in version 1.0, but it might be a feature for version 2.0, if browser-support is not as bad as I think and if I find a way to resolve the IDs completely in the browser.

**Comment by letorbi** [comment]
Version 2 will also rely on the HTTP-server to resolve module IDs - probably even more than version 1. Therefore I'm closing this issue.
