### ISSUE TITLE
Fix: make require work with web workers

### ISSUE THREAD

**Issue by sbeaupre** [letorbi/tarp.require#27]
To make tarp.require work from within a web worker, I had to add following changes:

```
var locationRef = location.protocol === 'blob:' ? location.origin : location.href;

var pwd = (new URL(id[0] == "." ? (parent ? parent.uri : locationRef) : config.paths[0], locationRef)).href;
```
When a blob: is detected as a protocol, it means we are in a worker thread and need to make sure we get the correct location.
(was too short to create a pull request)

It works also within workers in a standalone electron application.

**Comment by letorbi** [comment]
Thanks for reporting, I will try to fix it until the end of the week.

**Comment by letorbi** [comment]
I've tried to load and use Tarp.require in a web-worker and had no problems. The code I've used for testing is the following:

```
"use strict";
importScripts("../require.js");
Tarp.require({ expose: true });
var mod = require("module1");
console.log('Worker ' + mod.greet());
```

Actually a browser that provides `location.origin` in a web-worker should also provide `location.href`. At least Firefox and Chrome do (don't have access to Windows right now).

Can you please tell me in what browser the problem occurred?

**Comment by sbeaupre** [comment]
I used chrome & firefox on Mac. The problem is that in a webworker, location.href is refering to 'blob:'.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/447350/45684696-610b4200-bb47-11e8-8632-06e5fe0ec89e.png">

**Comment by letorbi** [comment]
Oh, now I see. I totally missed out that web-worker can also be loaded as blobs...

I've added a new config-option `root`, which can be used to override the root-URL that is used to resolve relative entries in the `paths` array (which is also a config option). I've choosen this solution over your approach, since the root config-option is more flexible that `location.origin`.

Use the following code to load Tarp.require in a web-worker blob:

```
importScripts("https://example.com/tarp.require/require.js");
Tarp.require({ main: "mainModule", root: "https://example.com/page/" });
```

Can you check-out the latest *master* and confirm that the problem is solved?
