### ISSUE TITLE
Can't access node_modules/@tarp when using express.static

### ISSUE THREAD

**Issue by MattCloward** [letorbi/tarp.require#29]
This probably isn't a bug, I'm just having trouble getting this to work for my particular website structure. Sorry if the answer is obvious, I've just gotten stuck and could use some help.
Structure:
node_modules
static
--js
----main.js
--index.html
index.js

I put the 2 lines in index.html to load in tarp, but I get this error:
`http://localhost:3000/node_modules/@tarp/require/require.min.js net::ERR_ABORTED 404 (Not Found)`
I beleive this is because of the following line in my index.js file, which serves up the website:
`app.use('/', express.static(path.join(__dirname, 'static')))`
This seems to append "static" to the beginning of all server paths, which is great to access my html file, but not for loading tarp. Any suggestions for how to fix this? Thanks!

**Comment by letorbi** [comment]
Hej Matt,

first of all you should check, how the request-URL actually looks like. You could do this either in the network-tab of your browser's developer console or in the logs of your webserver.

If 'static' is really appended to all request-URLs, I'm afraid you have to ask the developers of the application-framework you're using for help. I'd say it's quite likely that there is a way to prevent the appending of 'static' to certain URLs.

Please write me, if there is no such option and you need some special handling of the request-URLs inside Tarp.require to make it work with your framework.

Bye,
Torben

**Comment by letorbi** [comment]
PS: Could it be that *index.js* is providing the webserver that serves *index.html*? In that case, it is likely that the URLs requested by the browser are correct and that you only have to configure/fix the server-part of your webapp.

**Comment by MattCloward** [comment]
Thanks for the quick reply!
I'm using express js for the web app which I believe is pretty standard. Checking the request-URLs, they actually remove "static" from the URL as in they only check for folders and files inside that directory. That means that because my node_modules folder is outside the static folder (the equivalent of "page" in your tutorial), I can't path to it. I'll keep looking into it, but do you have any ideas of where I can look?
Thanks again!

**Comment by letorbi** [comment]
So I'd say the simplest solution would be to remove Tarp.require from the global *node_modules* folder (and maybe the *package.json* file as well). Then switch into the *static* folder and install tarp.require again:

```
npm uninstall --save @tarp/require
cd static
npm install --save @tarp/require
```
(If you don't have a *package.json* file, just don't add the `--save` option to the NPM callls.)

The resulting file structure should look like this:

* index.js
* package.json (list of modules for the server)
* node_modules
  * (express and maybe other modules for the server)
* static
  * index.html
  * package.json (list of modules for the website)
  * js
    * main.js
  * node_modules
    * @tarp
      * require
        * (files of Tarp.require)
    * (maybe other modules for the website)

**Comment by MattCloward** [comment]
Okay, I've set up the project like you suggested above. In my main.js file, I have two methods defined as follows:
`async function SubmitFormData() {
    ...
    var map = await createMap();
    ...
}

function createMap(fileContents) {
    var vcf = require('bionode-vcf/lib/index.js');
    var stream = require('stream/index.js')
    ...
}`
In my html file, I have a button that calls the SubmitFormData function when it is pressed. However, if I don't use
`<script src="js/main.js"></script>`
It say that the SubmitFormData function is not defined and if I do include the main.js file, it says:
`Uncaught (in promise) ReferenceError: require is not defined
    at createMap (VM677 main.js:78)
    at SubmitFormData (VM677 main.js:21)
    at HTMLButtonElement.onclick (index.html:225)`
Am I doing something wrong here or is there a reason require is still not defined?
Thanks for your patience!

**Comment by MattCloward** [comment]
Also, when "requiring" a module like "fs-extra" for example, do I have to change all of the requires inside the module to the absolute files they reference? I currently get errors for each require inside each module I import, because it can't find, say fs.js, when it should be looking for fs/index.js.

**Comment by letorbi** [comment]
Hi Matt,

first of all sorry for the extremely long response time. It seems that I've simply forgot to answer :/

>In my html file, I have a button that calls the SubmitFormData function when it is pressed. However, if I don't use <script src="js/main.js"></script>
It say that the SubmitFormData function is not defined and if I do include the main.js file, it says:
Uncaught (in promise) ReferenceError: require is not defined at createMap (VM677 main.js:78) at SubmitFormData (VM677 main.js:21) at HTMLButtonElement.onclick (index.html:225)

If you button uses something like `onclick="SubmitFormData()"`, it won't work, because `SubmitFormData()` is not part of the global scope. If a function is defined in a module, it is only visible inside the scope of the module unless it has been explicitly exported via `exports.myFunction = myFunction;`.

The reference error you are describing happen, because `require()` in not of the global scope as well. It available inside a module scope. The first module - often called main-module in the docs - is usually loaded via `Tarp.require({main: "./scripts/main"});`. All other modules would then be loaded from the main-module.

So how could you get your form working? You have two options:

The first option uses `addEventListerner()` instead of `onclick=` to set `SubmitFormData()` as a handler for click-events. Just set an `id` for your form-element, add the following line right below the definition of `SubmitFormData()` and everything should work as expected:

```
document.getElementById("MyForm").addEventListener("click", SubmitFormData);
```

The way above is the recommended one, but if you don't like it, you could also export `require()` to the global scope by loading Tarp.require via `Tarp.require({expose: true});`. This way you could set the onlick listener via `onclick="require('MyModule').SubmitFormData()"`, if the function is defined as `exports.SubmitFormData = async function SubmitFormData() { ... }`. But this would enforce the synchronous laoding of `MyModule` and is thus a bad practice.

> Also, when "requiring" a module like "fs-extra" for example, do I have to change all of the requires inside the module to the absolute files they reference? I currently get errors for each require inside each module I import, because it can't find, say fs.js, when it should be looking for fs/index.js.

Proper path resolving requires some confuguration on the server side. The [Path resolving section of the Readme](https://github.com/letorbi/tarp.require#path-resolving) explains the details.

I hope this answers your questions - better late than never ;) I'll close this issue for now. But please re-open it, if your questions are still not resolved.

Regards,
Torben
