### ISSUE TITLE
Add to bower

### ISSUE THREAD

**Issue by yuri-karadzhov** [letorbi/tarp.require#8]
It's good to have this library in [bower](http://bower.io)

**Comment by flawyte** [comment]
Upvote for Bower :+1:

**Comment by letorbi** [comment]
The new version of Smoothie, called [Tarp.require](https://github.com/letorbi/smoothie/tree/tarp) will have an NPM and a Bower package.

**Comment by letorbi** [comment]
After some thoughts, I've decided not to add a Bower package file for two resons:

* Even the Bower guys themselves recommend Yarn (which uses NPM) instead of their own tool now and I don't want to bloat the repo with stuff that will be obsolete soon.
* Bower doesn't support namespaces for packages and I don't want to have two different installation names for the Tarp.require package out in the wild.

Since bower depends on NPM it should be no big deal to install Tarp.require via NPM instead of Bower, so I hope my decision not to support bower is not a big hassle for you, and if you really need Bower support you could create your own *bower.json* file.

If you have good reasons why I should support Bower anyway, please reopen the issue and explain them to me.
